version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5000:5000"

  product-service:
    build:
      context: ./product-service
    ports:
      - "3000:3000"
    
  order-service:
    build:
      context: ./order-service
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
  
  mongo:
    image: mongo:latest

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
